version: '2'
services:
  static-host:
    container_name: numberstation_static_host
    build: .
    image: numberstation_static_host
    depends_on:
      - service
    # Remove comments if running without external routing or locally
    #ports:
      #- '80:80'
    volumes:
      - ./site:/var/www/site
  service:
    container_name: numberstation_service
    build: backend/.
    command: node service.js
    volumes:
      - ./backend:/home/node/numberspy
      - /home/node/numberspy/node_modules

# Uses external network with routing
networks:
  default:
    external:
      name: production